### ISSUE TITLE
Reconciliation w/ Fugue backend

### ISSUE THREAD

**Issue by webert6** [Nixtla/hierarchicalforecast#180]
After building forecasts at scale using the Fugue backend with Spark, we also need to reconcile at scale. Is there anything in the works to enable this?

**Comment by webert6** [comment]
For example, this is really slick:

```
backend = FugueBackend(spark, {'fugue.spark.use_pandas_udf':True})

# generate forecasts
sf = StatsForecast(
   models = [ Naive() ], # models to employ
   freq = 'D', 
   backend = backend # specify backend, if you want to run your pipeline locally, just remove it
)
y_pred = sf.forecast(
    df = y_hist, 
    h = 28
  ).cache()
```

It would be great to have something similar like this:

```
reconcilers = [
    BottomUp(),
    MinTrace(method='ols', nonnegative=True)
]
hrec = HierarchicalReconciliation(reconcilers=reconcilers, backend = backend)
Y_rec_df = hrec.reconcile(Y_hat_df=Y_hat_df, 
                          Y_df=Y_fitted_df, 
                          S=S_df, 
                          tags=tags)
```

**Comment by webert6** [comment]
Quick example:

It would be great if the aggregate function below was compatible with a pyspark dataframe with the ability create the same three objects (Y_df, S_df, tags).

![image](https://user-images.githubusercontent.com/54189065/231873635-9d4550f4-45af-452e-8799-9fa8c0f9b16c.png)

From which, we could pass Y_df (a spark dataframe) to forecast

![image](https://user-images.githubusercontent.com/54189065/231874178-191fc339-d43e-4ebc-b8fc-3705c94524af.png)

Then, pass the forecasts, summing matrix, and tags to the reconciliation method.

![image](https://user-images.githubusercontent.com/54189065/231875336-57b87001-d6e7-4500-baad-ce49eec97059.png)

**Comment by kdgutier** [comment]
Hey @webert6,

Thanks for using HierarchicalForecast, and thanks for the suggestion.
For the moment we don't support for spark distributed datasets, such features in the library would require substantial work. 

Ideas that need to be considered for large data reconciliation:
- The aggregation constraints matrix contained in `S_df` has a shape that scales quadratically `(n_aggregate+n_bottom) x (n_bottom)`. The step would be to make the associated `S` sparse.
- Some optimal reconciliation strategies scale cubicly, due to matrix inversions. We would need to apply dimensionality reduction and/or conjugate gradient inversion.
- In some cases the BottomUp reconciliation could be applied in a completely parallelized form using map reduce, this idea would require additional development and a forecast distribution representation compatible with such approach.

**Comment by kdgutier** [comment]
On another note, the creation of `S_df` and the hierarchical aggregation set uses numpy vectorized functions.
As long as the dataset fits in RAM it should be a fairly efficient method.

**Comment by webert6** [comment]
Thanks for the response @kdgutier! I will beef up our cluster and see if that can work. Hopefully applying some logical filtering beforehand can reduce enough of the load we put on the RAM. I am a lead for a service parts forecasting initiative for John Deere and see reconciliation has a valuable step in the process if we can make it work at scale. If you can imagine, there is a lot of history and a lot of parts to build this process around. 

I really appreciate the work being done in this space. It'll drive a lot a value for a lot of teams.
