### ISSUE TITLE
Add hyperparameter optimization capabilities

### ISSUE THREAD

**Issue by kdgutier** [Nixtla/hierarchicalforecast#25]
It would be beneficial for complex models like MinT-shr and ERM-lasso to inherit the [BaseEstimator](https://scikit-learn.org/stable/modules/generated/sklearn.base.BaseEstimator.html) sklearn class to help with the automated search of hyperparameters.

**Comment by elephaint** [comment]
- ERM-lasso is essentially a toy method, as it doesn't meaningfully work on anything larger than 10 time series due to the computational complexity. So hyperparam search is a no-go.
- MinT-shrink doesn't have any (meaningful) hyperparameters, the ridge parameter is only there to ascertain positive semi-defitiniteness of the correlation matrix (introducing a tiny bias), but in general it shouldn't be optimized. The choice of method in mint-shrink could be optimized though, but given the limited options I don't see the need to implement a automated search possibility for this.
